// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const bagDynamicColorPng = 'assets/images/bag-dynamic-color.png';
  static const boyDynamicColorPng = 'assets/images/boy-dynamic-color.png';
  static const chessDynamicColorPng = 'assets/images/chess-dynamic-color.png';
  static const flatColorIconsGooglePng = 'assets/images/flat-color-icons_google.png';
  static const giftDynamicColorPng = 'assets/images/gift-dynamic-color.png';
  static const girlDynamicColorPng = 'assets/images/girl-dynamic-color.png';
  static const gymDynamicColorPng = 'assets/images/gym-dynamic-color.png';
  static const minecraftDynamicColorPng = 'assets/images/minecraft-dynamic-color.png';
  static const notebookDynamicColorPng = 'assets/images/notebook-dynamic-color.png';
  static const onboarding01Png = 'assets/images/onboarding01.png';
  static const onboarding02Png = 'assets/images/onboarding02.png';
  static const onboarding03Png = 'assets/images/onboarding03.png';
  static const paintKitDynamicColorPng = 'assets/images/paint-kit-dynamic-color.png';
  static const rocketDynamicColorPng = 'assets/images/rocket-dynamic-color.png';
  static const startingPng = 'assets/images/starting.png';
  static const targetDynamicColorPng = 'assets/images/target-dynamic-color.png';
  static const teaCupDynamicColorPng = 'assets/images/tea-cup-dynamic-color.png';
}

class AssetsSvgs {

}

